name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: arduino/arduino-lint-action
        uses: arduino/arduino-lint-action@v1.0.0
        with:
          compliance: strict
          library-manager: update
